#server配置
server:
  port: 80                                        #启动端口号
  servlet:
    path: /crab                                  #项目名,请求根路径,如:www.bigfire.cn/crab/
#spring配置
spring:
  jackson:                                        #jackson配置
    date-format: yyyy-MM-dd HH:mm:ss              #时间格式化方式
    time-zone: GMT+8                              #解决时间相差8小时问题
  output:                                         #output控制台配置
    ansi:
      enabled: always                             #控制台 输出待颜色的配置
  datasource:                                     #数据库 配置
    type: com.alibaba.druid.pool.DruidDataSource  #数据库 连接池选择
    driver-class-name: com.mysql.jdbc.Driver      #数据库 驱动
    url: jdbc:mysql://localhost:3306/crab?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false  #本地地址
    username:                                     #数据库 用户名
    password:                                     #数据库 密码
#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml   #Mapper文件位置
  global-config:                                  #数据库相关配置
    db-config:
      id-type: AUTO                               #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      logic-delete-value: -1
      logic-not-delete-value: 0
      table-underline: true                       #驼峰下划线转换
    banner: false                                 #关闭mybatis-plus的banner
  configuration:                                  #原生配置
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
